server:
  error:
    include-stacktrace: 'never ' #exclude trace property in error response
    
spring:
  jpa:
    show-sql: "true"
  data:
    jpa:
      repositories:
        bootstrap-mode: "default"
  datasource:
    url: "jdbc:h2:mem:hihi"
  messages: #configure ResourceBundleMessageSource
    basename: 'internationalization/message ' #include all message*_.properties files
  security: #Spring Security configuration
   user:
    name: 'justa'
    password: 'cpulover'
  h2:
    console:
      enabled: "true"
  
    
management:
  endpoints:
    web:
      exposure:
        include: "*" #include all Actuator endpoints
        exclude: "beans"  #exclude beans endpoint
   
        
  
  